const http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const root=path.join(__dirname,'public');
http.createServer(async(req,res)=>{let pathname;try{pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname)}catch{res.writeHead(400);return res.end();}
if(['/api/payments','/api/calling','/api/auth-status'].includes(pathname)){
 res.status=function(code){this.statusCode=code;return this;};res.json=function(data){this.setHeader('Content-Type','application/json');this.end(JSON.stringify(data));};res.redirect=function(code,url){this.writeHead(code,{Location:url});this.end();};
 req.query=Object.fromEntries(new URL(req.url,'http://localhost').searchParams);
 try{let body='';for await(const chunk of req){body+=chunk;if(body.length>20000){res.status(413).json({error:'REQUEST_TOO_LARGE'});return;}}req.body=body?JSON.parse(body):{};await require('.'+pathname+'.js')(req,res);}catch{if(!res.writableEnded)res.status(400).json({error:'INVALID_REQUEST'});}return;
}
if(pathname==='/api/config'){res.setHeader('Content-Type','application/json');res.setHeader('Cache-Control','no-store');try{const c=JSON.parse(fs.readFileSync(path.join(__dirname,'config.local.json'),'utf8'));return res.end(JSON.stringify({url:c.url,publishableKey:c.publishableKey}));}catch{res.writeHead(503);return res.end('{"error":"BACKEND_NOT_CONFIGURED"}');}}
const file=path.resolve(root,'.'+(pathname==='/'?'/index.html':pathname));if(!file.startsWith(root+path.sep)){res.writeHead(403);return res.end();}fs.readFile(file,(err,data)=>{if(err){res.writeHead(404);return res.end('Not found');}res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'application/javascript; charset=utf-8','.svg':'image/svg+xml'})[path.extname(file)]||'application/octet-stream');res.setHeader('X-Content-Type-Options','nosniff');res.end(data);});}).listen(Number(process.env.PORT||4181),'127.0.0.1',()=>console.log('Connected preview: http://127.0.0.1:'+(process.env.PORT||4181)));
