import {createClient} from '@supabase/supabase-js';
import {randomUUID} from 'node:crypto';
import assert from 'node:assert/strict';
const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_PUBLISHABLE_KEY;
const admin=createClient(url,process.env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false}});
const users=[],clients=[],run=randomUUID(),password=randomUUID()+randomUUID();let productId,shopId,orderId,imagePath;
async function ok(p){const r=await p;if(r.error)throw new Error(r.error.message);return r.data;}
async function account(role){const email=`skb-${role}-${run}@example.invalid`;const {user}=await ok(admin.auth.admin.createUser({email,password,email_confirm:true}));users.push(user.id);const client=createClient(url,key,{auth:{persistSession:false}});await ok(client.auth.signInWithPassword({email,password}));clients.push(client);return {client,id:user.id};}
try{
const retailer=await account('retailer'),buyer=await account('buyer'),outsider=await account('outsider');
const shop=await ok(retailer.client.from('shops').insert({owner_id:retailer.id,name:'TEST ONLY — QA shop',contact_name:'Synthetic retailer',phone:'9800000000',province:'Madhesh',district:'Mahottari',municipality:'Pipra',ward:5,tole:'Test fixture'}).select().single());shopId=shop.id;
const p=await ok(retailer.client.from('products').insert({seller_id:retailer.id,shop_id:shop.id,title:'TEST ONLY — QA product',category:'clothing',description:'Synthetic integration fixture, not a real item for sale.',condition:'new',regular_price:1000,offer_price:800,offer_end:new Date(Date.now()+3600000).toISOString(),method:'checkout',status:'draft',province:'Madhesh',district:'Mahottari',municipality:'Pipra',pickup_address:'TEST ONLY',delivery_available:true,delivery_charge:100,cod_supported:true}).select().single());productId=p.id;
const v=await ok(retailer.client.from('variants').insert({product_id:p.id,size:'M',colour:'Green',stock:3}).select().single());imagePath=`${retailer.id}/${p.id}/${run}.png`;
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aD1sAAAAASUVORK5CYII=','base64');
await ok(retailer.client.storage.from('product-images').upload(imagePath,png,{contentType:'image/png'}));await ok(retailer.client.from('product_photos').insert({product_id:p.id,storage_path:imagePath,position:0}));await ok(retailer.client.from('products').update({status:'published'}).eq('id',p.id));
const anon=createClient(url,key,{auth:{persistSession:false}});assert.equal((await ok(anon.from('products').select('id').eq('id',p.id))).length,1);console.log('PASS retailer shop, image upload, published offer, anonymous browsing');
const address={name:'Synthetic buyer',phone:'9800000001',province:'Madhesh',district:'Mahottari',municipality:'Pipra',ward:'5',tole:'TEST ONLY'};
assert.ok((await buyer.client.rpc('place_cod_order',{items:[{variant_id:v.id,quantity:1}],delivery_address:address,expected_total:1})).error);assert.equal((await ok(retailer.client.from('variants').select('stock').eq('id',v.id).single())).stock,3);
orderId=await ok(buyer.client.rpc('place_cod_order',{items:[{variant_id:v.id,quantity:2}],delivery_address:address,expected_total:1700}));assert.equal(Number((await ok(retailer.client.from('orders').select('*').eq('id',orderId).single())).total),1700);assert.equal((await ok(retailer.client.from('variants').select('stock').eq('id',v.id).single())).stock,1);console.log('PASS variant COD checkout, trusted total, rollback, stock');
for(const status of ['accepted','shipped','delivered'])await ok(retailer.client.rpc('update_order_status',{order_id:orderId,next_status:status}));assert.equal((await ok(buyer.client.from('orders').select('status').eq('id',orderId).single())).status,'delivered');console.log('PASS seller fulfilment and buyer history');
assert.equal((await ok(outsider.client.from('orders').select('*').eq('id',orderId))).length,0);assert.equal((await ok(outsider.client.from('products').update({title:'Unauthorized'}).eq('id',p.id).select())).length,0);assert.ok((await outsider.client.rpc('update_order_status',{order_id:orderId,next_status:'cancelled'})).error);assert.ok((await outsider.client.from('admins').insert({user_id:outsider.id})).error);assert.equal((await ok(outsider.client.from('profiles').select('*').eq('id',buyer.id))).length,0);console.log('PASS unauthorized orders, profiles, seller writes and admin escalation blocked');
const classified=await ok(outsider.client.from('products').insert({seller_id:outsider.id,title:'TEST ONLY — classified',category:'other',description:'Synthetic classified fixture for verification only.',condition:'used',regular_price:500,method:'contact',status:'published',province:'Madhesh',district:'Mahottari',municipality:'Pipra',pickup_address:'TEST ONLY'}).select().single());await ok(outsider.client.from('products').delete().eq('id',classified.id));console.log('PASS individual classified listing');console.log('LIVE DATABASE FLOWS PASSED');
}finally{
if(orderId){await admin.from('order_items').delete().eq('order_id',orderId);await admin.from('orders').delete().eq('id',orderId);}if(imagePath)await admin.storage.from('product-images').remove([imagePath]);if(productId)await admin.from('products').delete().eq('id',productId);if(shopId)await admin.from('shops').delete().eq('id',shopId);for(const id of users)await admin.auth.admin.deleteUser(id);for(const c of clients)await c.auth.signOut();
}
