export async function adminPage(ctx){
 const {db,user,t,esc,layout,checked,root,notify,requireUser,money}=ctx;await requireUser();if(!await checked(db.rpc('is_admin')))throw Error(t('Admin पहुँच छैन।','Administrator access denied.'));
 const tables=['profiles','account_controls','products','shops','orders','reports','account_requests','listing_reviews','shop_reviews','categories','banners','platform_settings','payment_attempts','admin_audit'];
 const results=await Promise.all(tables.map(table=>checked(db.from(table).select('*').limit(500))));const data=Object.fromEntries(tables.map((name,i)=>[name,results[i]]));
 const p=data.platform_settings[0];
 const actionButton=(a,id,label)=>`<button class="button secondary" data-admin-action="${a}" data-id="${id}">${label}</button>`;
 const reason=`<label>${t('कारण / समीक्षा टिप्पणी','Reason / review notes')}<textarea id="admin-reason" minlength="3" maxlength="2000" placeholder="${t('कारबाही गर्नु अघि कारण लेख्नुहोस्','Enter a reason before taking action')}"></textarea></label>`;
 layout(`<h2>${t('प्रशासन','Administration')}</h2><p>${t('अधिकतम ५०० विवरण प्रति खण्ड देखाइएको छ।','Up to 500 records per section are shown.')}</p><p>${data.profiles.length} ${t('खाता','accounts')} · ${data.products.length} ${t('सामान','products')} · ${data.orders.length} ${t('अर्डर','orders')}</p><p>${t('पुगेका अर्डरको वास्तविक रकम','Actual delivered order total')}: ${money(data.orders.filter(o=>o.status==='delivered').reduce((sum,o)=>sum+Number(o.total),0))}</p>${reason}
 <details open><summary>${t('सेवा र moderation','Services and moderation')}</summary><form id="admin-settings"><label><input name="online_payments_enabled" type="checkbox" ${p.online_payments_enabled?'checked':''}>${t('Online payment सक्षम (merchant configuration आवश्यक)','Enable online payment (requires merchant configuration)')}</label><label><input name="moderation_enabled" type="checkbox" ${p.moderation_enabled?'checked':''}>${t('सामानमा Admin स्वीकृति आवश्यक','Require listing approval')}</label><label><input name="calls_enabled" type="checkbox" ${p.calls_enabled?'checked':''}>${t('इन्टरनेट कल सक्षम (TURN configuration आवश्यक)','Enable internet calls (requires TURN configuration)')}</label><button class="button">${t('सेटिङ सुरक्षित राख्नुहोस्','Save settings')}</button></form><a href="#market/call">${t('Support agent कल केन्द्र','Support agent call desk')}</a><p>${t('Merchant keys वा payment success यहाँबाट परिवर्तन हुँदैन।','Merchant keys and payment success cannot be edited here.')}</p></details>
 <details><summary>${t('ग्राहक र विक्रेता','Buyers and sellers')}</summary>${data.profiles.map(a=>{const suspended=data.account_controls.find(c=>c.user_id===a.id)?.suspended;return `<article>${esc(a.display_name||a.id)} · ${esc(a.phone)} · ${suspended?t('निलम्बित','Suspended'):t('सक्रिय','Active')}${actionButton(suspended?'restore':'suspend',a.id,suspended?t('पुनः सक्रिय','Restore'):t('निलम्बन','Suspend'))}</article>`;}).join('')}</details>
 <details><summary>${t('पसल समीक्षा','Shop reviews')}</summary>${data.shops.map(s=>`<article><strong>${esc(s.name)}</strong><p>${esc(s.contact_name)} · ${esc(s.phone)}<br>${esc(s.province)}, ${esc(s.district)}, ${esc(s.municipality)}-${s.ward}, ${esc(s.tole)}</p><p>${t('वास्तविक समीक्षा पछि मात्र verification दिनुहोस्।','Grant verification only after an actual review.')}</p>${actionButton('verify',s.id,t('समीक्षा पूरा — Verify','Review complete — verify'))}${actionButton('unverify',s.id,t('Verification हटाउनुहोस्','Remove verification'))}</article>`).join('')}</details>
 <details><summary>${t('सामान र अफर','Listings and offers')}</summary>${data.products.map(x=>`<article><a href="#market/product/${x.id}">${esc(x.title)}</a> · ${esc(x.status)}<p>${money(x.regular_price)} ${x.offer_price?`/ ${money(x.offer_price)} · ${esc(x.offer_end||'')}`:''} · ${esc(data.listing_reviews.find(r=>r.product_id===x.id)?.decision||t('समीक्षा बाँकी','Not reviewed'))}</p>${actionButton('approve',x.id,t('स्वीकृत','Approve'))}${actionButton('reject',x.id,t('अस्वीकृत','Reject'))}${actionButton('pause',x.id,t('रोक्नुहोस्','Pause'))}${actionButton('end-offer',x.id,t('अफर अन्त्य','End offer'))}</article>`).join('')}</details>
 <details><summary>${t('अर्डर र भुक्तानी','Orders and payments')}</summary>${data.orders.map(o=>`<article>${esc(o.id)} · ${esc(o.status)}<p>${money(o.total)} · ${esc(o.payment_method)} / ${esc(o.payment_status)}</p><p>${esc(o.address.name)} · ${esc(o.address.phone)} · ${esc(o.address.municipality)}-${esc(o.address.ward)}</p>${(o.payment_method!=='cod'&&o.payment_status!=='paid'?[]:({pending:['accepted'],accepted:['shipped'],shipped:['delivered']}[o.status]||[])).map(s=>actionButton('order-'+s,o.id,esc(s))).join('')}${o.payment_method==='cod'&&['pending','accepted'].includes(o.status)?actionButton('order-cancelled',o.id,t('रद्द','Cancel')):''}</article>`).join('')}<h3>${t('Gateway confirmation','Gateway confirmation')}</h3>${data.payment_attempts.map(a=>`<article>${esc(a.id)} · ${esc(a.provider)} · ${esc(a.status)} · ${money(a.amount)}<p>${esc(a.transaction_reference||t('पुष्टि बाँकी','Unconfirmed'))}</p></article>`).join('')}</details>
 <details><summary>${t('रिपोर्ट र उजुरी','Reports and requests')}</summary>${data.reports.map(r=>`<article><a href="#market/product/${r.product_id}">${esc(r.product_id)}</a><p>${esc(r.reason)}</p>${actionButton('pause',r.product_id,t('सामान रोक्नुहोस्','Pause listing'))}</article>`).join('')}${data.account_requests.map(r=>`<article>${esc(r.request_type)} · ${esc(r.status)}<p>${esc(r.body)}</p>${actionButton('review-request',r.id,t('समीक्षा गरियो','Mark reviewed'))}${actionButton('resolve-request',r.id,t('समाधान गरियो','Mark resolved'))}</article>`).join('')}</details>
 <details><summary>${t('वर्गहरू','Categories')}</summary><form id="admin-category"><label>ID<input name="id" pattern="[a-z][a-z0-9-]{1,40}" required></label><label>नेपाली<input name="name_ne" required maxlength="80"></label><label>English<input name="name_en" required maxlength="80"></label><button class="button">${t('वर्ग थप्नुहोस् / सम्पादन','Add / edit category')}</button></form>${data.categories.map(c=>`<article>${esc(c.name_ne)} / ${esc(c.name_en)} · ${esc(c.id)}${actionButton(c.enabled?'disable-category':'enable-category',c.id,c.enabled?t('रोक्नुहोस्','Disable'):t('सक्रिय','Enable'))}</article>`).join('')}</details>
 <details><summary>${t('मुखपृष्ठ banner','Homepage banners')}</summary><form id="admin-banner"><label>नेपाली<input name="title_ne" required maxlength="180"></label><label>English<input name="title_en" required maxlength="180"></label><label>${t('बजार link','Market link')}<input name="link" value="#market" pattern="#market(/[a-z0-9/-]*)?" required></label><button class="button">${t('Banner थप्नुहोस्','Add banner')}</button></form>${data.banners.map(b=>`<article>${esc(b.title_ne)} / ${esc(b.title_en)}${actionButton(b.active?'hide-banner':'show-banner',b.id,b.active?t('लुकाउनुहोस्','Hide'):t('देखाउनुहोस्','Show'))}</article>`).join('')}</details>
 <details><summary>${t('प्रशासन गतिविधि अभिलेख','Administration audit log')}</summary>${data.admin_audit.sort((a,b)=>b.id-a.id).map(a=>`<p>${esc(a.created_at)} · ${esc(a.entity)} · ${esc(a.operation)} · ${esc(a.record_id)}</p>`).join('')}</details>`);
 const run=async fn=>{try{await fn();await adminPage(ctx);}catch(e){notify(e.message);}};
 root.querySelector('#admin-settings').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);run(()=>checked(db.from('platform_settings').update({online_payments_enabled:f.has('online_payments_enabled'),moderation_enabled:f.has('moderation_enabled'),calls_enabled:f.has('calls_enabled')}).eq('id',true)));};
 root.querySelector('#admin-category').onsubmit=e=>{e.preventDefault();run(()=>checked(db.from('categories').upsert({...Object.fromEntries(new FormData(e.target)),enabled:true})));};
 root.querySelector('#admin-banner').onsubmit=e=>{e.preventDefault();run(()=>checked(db.from('banners').insert(Object.fromEntries(new FormData(e.target)))));};
 root.querySelectorAll('[data-admin-action]').forEach(button=>button.onclick=()=>run(async()=>{const a=button.dataset.adminAction,id=button.dataset.id,reason=root.querySelector('#admin-reason').value.trim();if(['suspend','restore','approve','reject','verify','unverify'].includes(a)&&reason.length<3)throw Error(t('पहिले समीक्षा कारण लेख्नुहोस्।','Enter review notes first.'));
 if(['suspend','restore'].includes(a)){if(id===user.id)throw Error(t('आफ्नै खाता निलम्बन गर्न मिल्दैन।','You cannot suspend yourself.'));await checked(db.from('account_controls').upsert({user_id:id,suspended:a==='suspend',reason,updated_by:user.id,updated_at:new Date().toISOString()}));}
 else if(['verify','unverify'].includes(a))await checked(db.from('shop_reviews').upsert({shop_id:id,reviewed_by:user.id,verified:a==='verify',notes:reason,reviewed_at:new Date().toISOString()}));
 else if(['approve','reject'].includes(a)){await checked(db.from('listing_reviews').upsert({product_id:id,decision:a==='approve'?'approved':'rejected',reason,reviewed_by:user.id,reviewed_at:new Date().toISOString()}));await checked(db.from('products').update({status:a==='approve'?'published':'paused'}).eq('id',id));}
 else if(a==='pause')await checked(db.from('products').update({status:'paused'}).eq('id',id));
 else if(a==='end-offer')await checked(db.from('products').update({offer_price:null,offer_start:null,offer_end:null}).eq('id',id));
 else if(a.startsWith('order-'))await checked(db.rpc('update_order_status',{order_id:id,next_status:a.slice(6)}));
 else if(a.endsWith('request'))await checked(db.from('account_requests').update({status:a==='resolve-request'?'resolved':'reviewed'}).eq('id',id));
 else if(a.endsWith('category'))await checked(db.from('categories').update({enabled:a==='enable-category'}).eq('id',id));
 else if(a.endsWith('banner'))await checked(db.from('banners').update({active:a==='show-banner'}).eq('id',id));
 }));
}
