export async function communityPage(ctx,page,parts){
 const {db,user,t,esc,layout,checked,root,notify,requireUser,money}=ctx;
 if(!['favourites','inbox','chat','reviews','review','requests','admin'].includes(page))return false;
 if(page==='reviews'){const rows=await checked(db.from('reviews').select('*').eq('product_id',parts[2]));layout(`<h2>${t('खरिदपछिका समीक्षा','Purchase reviews')}</h2>${rows.map(r=>`<article>${r.rating}/5<p>${esc(r.body)}</p></article>`).join('')||`<p>${t('समीक्षा छैन।','No reviews yet.')}</p>`}`);return true;}
 await requireUser();
 if(page==='favourites'){const rows=await checked(db.from('favourites').select('*,products(*)').eq('user_id',user.id));layout(`<h2>${t('मनपर्ने सामान','Favourites')}</h2>${rows.map(r=>r.products?`<article><a href="#market/product/${r.product_id}">${esc(r.products.title)}</a><button class="text-button" data-remove-favourite="${r.product_id}">${t('हटाउनुहोस्','Remove')}</button></article>`:'').join('')||`<p>${t('मनपर्ने सूची खाली छ।','No favourites yet.')}</p>`}`);root.querySelectorAll('[data-remove-favourite]').forEach(b=>b.onclick=async()=>{await checked(db.from('favourites').delete().eq('user_id',user.id).eq('product_id',b.dataset.removeFavourite));await communityPage(ctx,page,parts);});return true;}
 if(page==='inbox'){const rows=await checked(db.from('messages').select('*').order('created_at',{ascending:false}).limit(100));layout(`<h2>${t('सन्देश र inquiries','Messages & inquiries')}</h2>${rows.map(r=>`<article><p>${esc(r.body)}</p><small>${esc(new Date(r.created_at).toLocaleString())}</small><a class="text-link" href="#market/chat/${r.product_id}/${r.buyer_id}">${t('कुराकानी खोल्नुहोस्','Open conversation')}</a></article>`).join('')||`<p>${t('सन्देश छैन।','No messages yet.')}</p>`}`);return true;}
 if(page==='chat'){const p=await checked(db.from('products').select('id,seller_id,title').eq('id',parts[2]).single()),buyerId=p.seller_id===user.id?parts[3]:user.id;if(!buyerId)throw Error(t('Inbox बाट कुराकानी खोल्नुहोस्।','Open a conversation from your inbox.'));const rows=await checked(db.from('messages').select('*').eq('product_id',p.id).eq('buyer_id',buyerId).order('created_at'));layout(`<h2>${esc(p.title)} — ${t('कुराकानी','Conversation')}</h2>${rows.map(r=>`<article><small>${r.sender_id===user.id?t('तपाईं','You'):t('अर्को व्यक्ति','Other participant')}</small><p>${esc(r.body)}</p></article>`).join('')}<form id="send-message"><label>${t('सन्देश','Message')}<input name="body" maxlength="2000" required></label><button class="button">${t('पठाउनुहोस्','Send')}</button></form>`);root.querySelector('#send-message').onsubmit=async e=>{e.preventDefault();try{await checked(db.from('messages').insert({product_id:p.id,buyer_id:buyerId,seller_id:p.seller_id,sender_id:user.id,body:new FormData(e.target).get('body')}));await communityPage(ctx,page,parts);}catch(e){notify(e.message);}};return true;}
 if(page==='review'){const item=await checked(db.from('order_items').select('*').eq('id',parts[2]).single());layout(`<h2>${t('खरिदको समीक्षा','Review your purchase')}</h2><form id="purchase-review"><label>${t('अंक','Rating')}<select name="rating">${[5,4,3,2,1].map(n=>`<option>${n}</option>`).join('')}</select></label><label>${t('समीक्षा','Review')}<input name="body" minlength="3" maxlength="2000" required></label><button class="button">${t('समीक्षा राख्नुहोस्','Submit review')}</button></form>`);root.querySelector('#purchase-review').onsubmit=async e=>{e.preventDefault();try{const f=new FormData(e.target);await checked(db.from('reviews').insert({order_item_id:item.id,buyer_id:user.id,product_id:item.product_id,rating:Number(f.get('rating')),body:f.get('body')}));location.hash='market/orders';}catch(e){notify(e.message);}};return true;}
 if(page==='requests'){const rows=await checked(db.from('account_requests').select('*').eq('user_id',user.id).order('created_at',{ascending:false}));layout(`<h2>${t('सहयोग / फिर्ता / खाता मेटाउने अनुरोध','Support / returns / account deletion requests')}</h2><form id="request-form"><label>${t('प्रकार','Type')}<select name="request_type"><option value="complaint">${t('उजुरी','Complaint')}</option><option value="return">${t('फिर्ता अनुरोध','Return request')}</option><option value="deletion">${t('खाता मेटाउने अनुरोध','Account deletion request')}</option></select></label><label>${t('विवरण र अर्डर नम्बर','Details and order reference')}<input name="body" minlength="10" maxlength="3000" required></label><button class="button">${t('अनुरोध पठाउनुहोस्','Submit request')}</button></form>${rows.map(r=>`<article>${esc(r.request_type)} · ${esc(r.status)}<p>${esc(r.body)}</p></article>`).join('')}`);root.querySelector('#request-form').onsubmit=async e=>{e.preventDefault();try{await checked(db.from('account_requests').insert({...Object.fromEntries(new FormData(e.target)),user_id:user.id}));await communityPage(ctx,page,parts);}catch(e){notify(e.message);}};return true;}
 if(page==='admin'){if(!await checked(db.rpc('is_admin')))throw Error(t('Admin पहुँच छैन।','Administrator access denied.'));const [products,shops,orders,reports,requests]=await Promise.all(['products','shops','orders','reports','account_requests'].map(table=>checked(db.from(table).select('*').limit(500))));layout(`<h2>${t('Admin dashboard','Admin dashboard')}</h2><p>${products.length} ${t('सामान','products')} · ${shops.length} ${t('पसल','shops')} · ${orders.length} ${t('अर्डर','orders')}</p><p>${t('Delivered अर्डर रकम','Delivered order total')}: ${money(orders.filter(o=>o.status==='delivered').reduce((n,o)=>n+Number(o.total),0))}</p><h3>${t('Listings व्यवस्थापन','Manage listings')}</h3>${products.map(p=>`<article>${esc(p.title)} · ${esc(p.status)}<button class="text-button" data-pause="${p.id}">${t('रोक्नुहोस्','Pause')}</button></article>`).join('')}<h3>${t('Reported listings','Reported listings')}</h3>${reports.map(r=>`<article><a href="#market/product/${r.product_id}">${esc(r.product_id)}</a><p>${esc(r.reason)}</p></article>`).join('')}<h3>${t('सहयोग अनुरोध','Support requests')}</h3>${requests.map(r=>`<article>${esc(r.request_type)} · ${esc(r.status)}<p>${esc(r.body)}</p><button class="text-button" data-resolve="${r.id}">${t('समाधान भयो','Resolve')}</button></article>`).join('')}`);root.querySelectorAll('[data-pause]').forEach(b=>b.onclick=async()=>{await checked(db.from('products').update({status:'paused'}).eq('id',b.dataset.pause));await communityPage(ctx,page,parts);});root.querySelectorAll('[data-resolve]').forEach(b=>b.onclick=async()=>{await checked(db.from('account_requests').update({status:'resolved'}).eq('id',b.dataset.resolve));await communityPage(ctx,page,parts);});return true;}
 return false;
}
