export function contactOrderBlock(p,{t,esc,money,activePrice}){
 const digits=value=>String(value||'').replace(/\D/g,'');
 const normalize=value=>{let n=digits(value);if(/^9\d{9}$/.test(n))n='977'+n;return /^9779\d{9}$/.test(n)?n:null;};
 const phone=normalize(p.shops?.phone),whatsapp=normalize(p.shops?.whatsapp);
 const phoneTarget=phone||'9779807605076',waTarget=whatsapp||'9779761658442';
 return `<section class="contact-order"><h3>${t('फोन वा WhatsApp बाट अर्डर सोध्नुहोस्','Order enquiry by phone or WhatsApp')}</h3><label>${t('संख्या','Quantity')}<input id="contact-quantity" type="number" min="1" max="100" value="1"></label><div class="actions"><a class="button secondary" href="tel:+${phoneTarget}">${phone?t('विक्रेतालाई फोन','Call seller'):t('अर्डर सहयोगलाई फोन','Call order support')}</a><a class="button" id="whatsapp-order" data-number="${waTarget}" href="https://wa.me/${waTarget}" target="_blank" rel="noopener">${whatsapp?t('विक्रेतालाई WhatsApp','WhatsApp seller'):t('WhatsApp अर्डर सहयोग','WhatsApp order support')}</a></div><p>${t('फोनमा मोबाइल कम्पनीको शुल्क र WhatsApp मा डेटा शुल्क लाग्न सक्छ। यो अर्डर अनुरोध हो; stock, delivery र अन्तिम रकम विक्रेता/सहयोगले पुष्टि गरेपछि मात्र अर्डर हुन्छ। Cart checkout बाट राखेको COD अर्डर मात्र My Orders मा स्वतः देखिन्छ।','Carrier/data charges may apply. This sends an enquiry; stock, delivery and final total need seller/support confirmation. Only COD orders placed through checkout appear automatically in My Orders.')}</p></section>`;
}
export function bindContactOrder(p,{root,t,money,activePrice}){
 const link=root.querySelector('#whatsapp-order');if(!link)return;
 link.onclick=()=>{const quantity=Math.max(1,Math.min(100,Math.trunc(Number(root.querySelector('#contact-quantity').value)||1)));const variant=p.variants.find(v=>v.id===root.querySelector('#variant')?.value);const url=new URL(location.href);url.hash='market/product/'+p.id;const message=[t('SastoKinBech अर्डर अनुरोध','SastoKinBech order enquiry'),p.title,variant?[variant.size,variant.colour].filter(Boolean).join(' / '):'',`${t('संख्या','Quantity')}: ${quantity}`,`${t('प्रति सामान मूल्य','Unit price')}: ${money(activePrice(p))}`,`${t('सामानको रकम','Subtotal')}: ${money(activePrice(p)*quantity)}`,url.href,t('कृपया stock, delivery शुल्क, COD र जम्मा रकम पुष्टि गर्नुहोस्।','Please confirm stock, delivery charges, COD and total payable.')].filter(Boolean).join('\n');link.href='https://wa.me/'+link.dataset.number+'?text='+encodeURIComponent(message);};
}
