const messages={PAYMENT_UNAVAILABLE:['यो भुक्तानी सेवा कन्फिगर भएको छैन। COD रोज्नुहोस्।','This payment service is not configured. Choose COD.'],PAYMENT_AMOUNT_MISMATCH:['रकम पुष्टि मिलेन। सहयोगमा सम्पर्क गर्नुहोस्।','Payment amount verification failed. Contact support.'],PAYMENT_NOT_INITIATED:['भुक्तानी सुरु भएको पुष्टि छैन। सहयोगमा सम्पर्क गर्नुहोस्।','Payment initiation is unconfirmed. Contact support.'],PAYMENT_FAILED:['भुक्तानी पुष्टि हुन सकेन। सहयोगमा सम्पर्क गर्नुहोस्।','Payment could not be verified. Contact support.']};
export async function paymentApi(db,action,body,t){const session=(await db.auth.getSession()).data.session;const r=await fetch('/api/payments?action='+action,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',...(session?{Authorization:'Bearer '+session.access_token}:{})},...(body?{body:JSON.stringify(body)}:{})});const data=await r.json();if(!r.ok)throw Error(messages[data.error]?t(...messages[data.error]):data.error);return data;}
export async function paymentPage(ctx,parts){
 const {db,t,esc,layout,root,notify,requireUser,checked,money}=ctx;await requireUser();
 const a=await checked(db.from('payment_attempts').select('*').eq('id',parts[2]).single());
 layout(`<h2>${t('भुक्तानी पुष्टि','Payment verification')}</h2><p>${esc(a.provider)} · ${money(a.amount)}</p><p>${a.status==='paid'?t('सेवाबाट पुष्टि भएको भुक्तानी।','Payment verified with the provider.'):t('भुक्तानी अझै पुष्टि भएको छैन। रकम काटिएको भए फेरि नतिर्नुहोस्।','Payment is not yet verified. If money was deducted, do not pay again.')}</p><button id="verify-payment" class="button">${t('अवस्था जाँच्नुहोस्','Check payment status')}</button><a href="#market/orders">${t('मेरा अर्डर','My orders')}</a>`);
 root.querySelector('#verify-payment').onclick=async e=>{e.target.disabled=true;try{const r=await paymentApi(db,'verify',{attempt:a.id},t);notify(r.status==='paid'?t('भुक्तानी पुष्टि भयो।','Payment verified.'):r.status==='failed'?t('सेवाबाट असफल पुष्टि भयो; अर्डर रद्द र stock फिर्ता गरियो।','Provider confirmed failure; the order was cancelled and stock restored.'):t('पुष्टि बाँकी छ। सहयोगमा सम्पर्क गर्नुहोस्।','Verification is pending. Contact support.'));}catch(e){notify(e.message);}finally{root.querySelector('#verify-payment').disabled=false;}};
}
export function gatewayRedirect(result,root){
 if(result.redirect){location.assign(result.redirect);return;}
 const f=document.createElement('form');f.method='POST';f.action=result.form.action;for(const [name,value]of Object.entries(result.form.fields)){const input=document.createElement('input');input.type='hidden';input.name=name;input.value=value;f.append(input);}root.append(f);f.submit();
}
export async function paymentMethodsPage({db,t,esc,layout}){
 const {methods}=await paymentApi(db,'methods',null,t);
 layout(`<h2>${t('भुक्तानी विधिहरू','Payment methods')}</h2><p>${t('Checkout मा सामानको विक्रेताले समर्थन गरेका र सक्रिय भएका विधि मात्र प्रयोग गर्न मिल्छ।','At checkout, use only active methods supported for the seller’s products.')}</p><div class="payment-grid"><article class="payment-card"><strong>Cash on Delivery · COD</strong><p>${t('सामान प्राप्त गर्दा नगद तिर्नुहोस्। विक्रेताले COD समर्थन गरेको सामानमा मात्र उपलब्ध।','Pay cash on delivery. Available only for products whose seller supports COD.')}</p><span class="payment-state">${t('योग्य सामानमा उपलब्ध','Available for eligible products')}</span></article>${methods.map(m=>`<article class="payment-card"><strong>${esc(m.name)}</strong><span class="payment-state ${m.available?'':'pending'}">${m.available?(m.sandbox?t('परीक्षण मात्र','Test mode only'):t('सक्रिय','Active')):t('अहिले उपलब्ध छैन','Currently unavailable')}</span><p>${m.id==='khalti'?t('IME Pay अहिले Khalti by IME मा समाहित छ। एउटै Khalti gateway प्रयोग हुन्छ।','IME Pay has merged into Khalti by IME. It uses the Khalti gateway.'):m.id==='cards'?t('Visa/Mastercard का लागि बैंकको सुरक्षित merchant gateway आवश्यक छ। कार्ड नम्बर यस वेबसाइटमा संकलन गरिँदैन।','Visa/Mastercard requires a bank merchant gateway. This website does not collect card numbers.'):t('आधिकारिक merchant सेवा र सुरक्षित भुक्तानी पुष्टि आवश्यक छ।','Requires official merchant service and secure payment verification.')}</p></article>`).join('')}</div><p>${t('Online सेवाहरू सक्रिय गर्न merchant स्वीकृति र credentials आवश्यक छन्। रकम काटिएको screenshot मात्रलाई सफल भुक्तानी मानिँदैन।','Online services need merchant approval and credentials. A payment screenshot alone does not confirm successful payment.')}</p><a class="button" href="#market">${t('सामान हेर्नुहोस्','Browse products')}</a>`);
}
