export function passwordControls(root,t){
 root.querySelectorAll('input[type=password]').forEach((input,index)=>{
 input.id=input.id||'password-'+index;input.autocomplete='current-password';
 const toggle=document.createElement('button');toggle.type='button';toggle.className='button secondary';toggle.setAttribute('aria-controls',input.id);toggle.setAttribute('aria-pressed','false');toggle.textContent=t('पासवर्ड देखाउनुहोस्','Show password');input.after(toggle);
 toggle.onclick=()=>{const show=input.type==='password';input.type=show?'text':'password';toggle.setAttribute('aria-pressed',String(show));toggle.textContent=show?t('पासवर्ड लुकाउनुहोस्','Hide password'):t('पासवर्ड देखाउनुहोस्','Show password');};
 });
}
export function phoneForm(t){return `<section><h3>${t('फोन नम्बर र OTP बाट login / दर्ता','Sign in / register by phone OTP')}</h3><p>${t('SMS सेवा configured भएमा मात्र OTP आउँछ। OTP वा password अरूलाई नदिनुहोस्।','OTP delivery requires configured SMS service. Never share your OTP or password.')}</p><form id="phone-send"><label>${t('नेपालको मोबाइल नम्बर','Nepal mobile number')}<input name="phone" type="tel" autocomplete="tel" placeholder="98XXXXXXXX" required></label><button class="button">${t('OTP पठाउनुहोस्','Send OTP')}</button></form><form id="phone-verify" hidden><label>${t('SMS मा आएको OTP','OTP received by SMS')}<input name="token" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6,8}" maxlength="8" required></label><button class="button">${t('OTP पुष्टि गरेर login','Verify OTP and sign in')}</button></form></section>`;}
export function bindPhone({root,db,t,notify,onSuccess}){
 let sentPhone,lastSent=0;const send=root.querySelector('#phone-send'),verify=root.querySelector('#phone-verify');
 send.onsubmit=async e=>{e.preventDefault();const n=String(new FormData(send).get('phone')).replace(/[\s()+-]/g,'').replace(/^977/,'');if(!/^9[78]\d{8}$/.test(n)){notify(t('मान्य नेपाली मोबाइल नम्बर राख्नुहोस्।','Enter a valid Nepal mobile number.'));return;}if(Date.now()-lastSent<60000){notify(t('फेरि OTP माग्न १ मिनेट पर्खनुहोस्।','Wait one minute before requesting another OTP.'));return;}const button=e.submitter;button.disabled=true;try{const phone='+977'+n;const r=await db.auth.signInWithOtp({phone});if(r.error)throw r.error;sentPhone=phone;lastSent=Date.now();verify.hidden=false;notify(t('SMS मा आएको OTP राख्नुहोस्।','Enter the OTP received by SMS.'));}catch{notify(t('OTP पठाउन सकिएन। SMS सेवा उपलब्ध नभएको वा अनुरोध सीमित भएको हुन सक्छ। Email login प्रयोग गर्नुहोस्।','OTP could not be sent. SMS may be unconfigured or rate limited. Use email login.'));}finally{button.disabled=false;}};
 verify.onsubmit=async e=>{e.preventDefault();if(!sentPhone)return;const button=e.submitter;button.disabled=true;try{const r=await db.auth.verifyOtp({phone:sentPhone,token:String(new FormData(verify).get('token')).trim(),type:'sms'});if(r.error||!r.data.session)throw Error();await onSuccess(r.data.user);}catch{notify(t('OTP गलत वा म्याद सकिएको छ।','OTP is invalid or expired.'));}finally{button.disabled=false;}};
}
