const icons={clothing:'♧',electronics:'⌨',phones:'▯',home:'⌂',beauty:'✧',groceries:'♧',footwear:'◒',accessories:'◇',other:'＋'};
export async function renderStorefront(ctx){
 const {db,t,esc,checked,money,activePrice}=ctx;
 const empty=(ne,en,link='#market/sell')=>`<div class="empty-state"><p>${t(ne,en)}</p><a href="${link}">${t('आफ्नो सामान राख्नुहोस् →','List your item →')}</a></div>`;
 try{
 const [cats,products,shops,banners]=await Promise.all([checked(db.from('categories').select('*').eq('enabled',true)),checked(db.from('products').select('*,product_photos(*)').eq('status','published').order('created_at',{ascending:false}).limit(60)),checked(db.from('shops').select('id,name,description,district,municipality,logo_path').order('created_at',{ascending:false}).limit(8)),checked(db.from('banners').select('*').eq('active',true))]);
 const category=c=>`<a href="#market/browse?category=${encodeURIComponent(c.id)}" class="category-tile"><span aria-hidden="true">${icons[c.id]||'◇'}</span>${esc(t(c.name_ne,c.name_en))}</a>`;
 document.querySelector('#categories').innerHTML=cats.map(category).join('');document.querySelector('#side-categories').innerHTML=cats.map(c=>`<a href="#market/browse?category=${encodeURIComponent(c.id)}"><span aria-hidden="true">${icons[c.id]||'◇'}</span>${esc(t(c.name_ne,c.name_en))}</a>`).join('');
 const card=p=>{const photo=p.product_photos.sort((a,b)=>a.position-b.position)[0],price=activePrice(p);return `<a class="product-card" href="#market/product/${p.id}">${photo?`<img loading="lazy" src="${esc(db.storage.from('product-images').getPublicUrl(photo.storage_path).data.publicUrl)}" alt="${esc(p.title)}">`:`<div class="image-placeholder" aria-label="${t('फोटो उपलब्ध छैन','No photo available')}">◇</div>`}<h3>${esc(p.title)}</h3><p>${money(price)}</p>${price<Number(p.regular_price)?`<small><del>${money(p.regular_price)}</del> −${Math.round(100*(1-price/Number(p.regular_price)))}%</small>`:''}<small>${esc(p.district)} · ${p.method==='checkout'?t('Checkout','Checkout'):t('सम्पर्क गरेर किन्नुहोस्','Contact seller')}</small></a>`;};
 const offers=products.filter(p=>activePrice(p)<Number(p.regular_price));document.querySelector('#home-offers').innerHTML=offers.slice(0,6).map(card).join('')||empty('अहिले कुनै सक्रिय अफर छैन।','There are no active offers at the moment.');document.querySelector('#home-products').innerHTML=products.slice(0,18).map(card).join('')||empty('अहिले प्रकाशित सामान छैन। पहिलो सामान तपाईंले राख्न सक्नुहुन्छ।','No published products yet. You can list the first item.');
 document.querySelector('#home-shops').innerHTML=shops.map(s=>`<a href="#market/store/${s.id}" class="shop-card"><span aria-hidden="true">⌂</span><h3>${esc(s.name)}</h3><p>${esc(s.municipality)}, ${esc(s.district)}</p><small>${esc(s.description.slice(0,100))}</small></a>`).join('')||empty('पसल दर्ता भएपछि यहाँ देखिन्छ।','Registered retailer shops appear here.','#market/shop');
 document.querySelector('#homepage-banners').innerHTML=banners.map(b=>`<a href="${esc(b.link)}">${esc(t(b.title_ne,b.title_en))} →</a>`).join('');
 }catch(e){for(const id of ['home-products','home-offers','home-shops'])document.getElementById(id).innerHTML=`<div class="empty-state"><p>${t('बजारको डेटा लोड हुन सकेन।','Unable to load marketplace data.')}</p><a href="#market">${t('बजारमा फेरि प्रयास गर्नुहोस्','Try the marketplace')}</a></div>`;}
}
export async function storeProfile(ctx,id){const {db,t,esc,checked,layout,money,activePrice}=ctx;const s=await checked(db.from('shops').select('*').eq('id',id).single()),products=await checked(db.from('products').select('*').eq('shop_id',id).eq('status','published'));layout(`<h2>${esc(s.name)}</h2><p class="seller-copy">${esc(s.description)}</p><p>${esc(s.province)}, ${esc(s.district)}, ${esc(s.municipality)}-${s.ward}, ${esc(s.tole)}<br>${esc(s.landmark)}</p><p>${t('खुल्ने समय','Opening hours')}: ${esc(s.opening_hours)}<br>${t('Delivery क्षेत्र','Delivery areas')}: ${esc(s.delivery_areas)}</p><p>${t('फिर्ता सर्त','Return policy')}: ${esc(s.return_policy)}</p><div class="actions"><a class="button secondary" href="tel:${esc(s.phone)}">${t('पसललाई फोन','Call shop')}</a>${s.whatsapp?`<a class="button secondary" href="https://wa.me/${esc(s.whatsapp.replace(/\D/g,''))}">WhatsApp</a>`:''}</div><h3>${t('पसलका सामान','Shop products')}</h3><div class="product-grid">${products.map(p=>`<a class="product-card" href="#market/product/${p.id}"><h3>${esc(p.title)}</h3><p>${money(activePrice(p))}</p></a>`).join('')||`<p>${t('प्रकाशित सामान छैन।','No published products.')}</p>`}</div>`);}
